/*
 * Morgan Yeh 
 * 2024/07/15
 * Screen to select which algorithms to view
 */
package cube.trainer;

import java.awt.Color;
import java.io.File;
import java.io.FileInputStream;
import java.util.ArrayList;
import java.util.Scanner;
import javax.swing.JOptionPane;

/**
 *
 * @author morga
 */
public class AlgorithmSelect extends javax.swing.JFrame {
    private MainMenu m;
    private PLLAlgList p;
    private PLL2AlgList p2;
    private OLLAlgList o;
    private OLL2AlgList o2;
    
    
    //arrayLists of each alg set
    private ArrayList<Algorithm> algs;
    
    /**
     * Creates new form AlgorithmSelect
     */
    public AlgorithmSelect(MainMenu m) {
        initComponents();
        this.m = m;
        
        //change background color
        this.getContentPane().setBackground(new Color(102,204,255));
        
        //make frame not resizable
        setResizable(false);
    }
    
    public static ArrayList<Algorithm> loadArray(String file) {
        ArrayList<Algorithm> a = new ArrayList();
        
        //read from data file
        try {
            FileInputStream in = new FileInputStream(System.getProperty("user.dir") + "/src/Data Files/" + file); 
            Scanner s = new Scanner(in);
            
            //read while file has more lines
            while(s.hasNextLine()) {
                //get attributes for Algorithm object
                String set = s.nextLine();
                String group = s.nextLine();
                String name = s.nextLine();
                
                String[] setups = new String[4];
                //get setup moves for OLL and algs only
                if (file.equals("PLL.txt") || file.equals("OLL.txt")) {
                    for (int i = 0; i < setups.length; i++) {
                        setups[i] = s.nextLine();
                    }
                }
                
                String alg = s.nextLine();
                String imgFile = s.nextLine();
                boolean learned = Boolean.parseBoolean(s.nextLine());
                
                //create Algorithm object and add to ArrayList
                Algorithm c = new Algorithm(set, group, name, setups, alg, imgFile, learned);
                a.add(c);
            }
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        
        return a;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        btnOLL = new javax.swing.JButton();
        btnPLL = new javax.swing.JButton();
        btn2LookPLL = new javax.swing.JButton();
        btn2LookOLL1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("DengXian", 1, 80)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Algorithms");

        btnBack.setBackground(new java.awt.Color(153, 153, 153));
        btnBack.setFont(new java.awt.Font("DengXian", 1, 36)); // NOI18N
        btnBack.setText("Back");
        btnBack.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnOLL.setBackground(new java.awt.Color(0, 153, 255));
        btnOLL.setFont(new java.awt.Font("DengXian", 1, 48)); // NOI18N
        btnOLL.setText("OLL");
        btnOLL.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));
        btnOLL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOLLActionPerformed(evt);
            }
        });

        btnPLL.setBackground(new java.awt.Color(0, 153, 255));
        btnPLL.setFont(new java.awt.Font("DengXian", 1, 48)); // NOI18N
        btnPLL.setText("PLL");
        btnPLL.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));
        btnPLL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPLLActionPerformed(evt);
            }
        });

        btn2LookPLL.setBackground(new java.awt.Color(0, 153, 255));
        btn2LookPLL.setFont(new java.awt.Font("DengXian", 1, 48)); // NOI18N
        btn2LookPLL.setText("2-Look PLL");
        btn2LookPLL.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));
        btn2LookPLL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2LookPLLActionPerformed(evt);
            }
        });

        btn2LookOLL1.setBackground(new java.awt.Color(0, 153, 255));
        btn2LookOLL1.setFont(new java.awt.Font("DengXian", 1, 48)); // NOI18N
        btn2LookOLL1.setText("2-Look OLL");
        btn2LookOLL1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));
        btn2LookOLL1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2LookOLL1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(197, 197, 197)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn2LookOLL1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                    .addComponent(btnOLL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 289, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn2LookPLL, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                    .addComponent(btnPLL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(194, 194, 194))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(430, 430, 430))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jLabel1)
                .addGap(91, 91, 91)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn2LookOLL1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn2LookPLL, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(93, 93, 93)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOLL, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPLL, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addComponent(btnBack)
                .addGap(45, 45, 45))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        //go back to main menu
        m.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btn2LookPLLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2LookPLLActionPerformed
        //get algs algs
        algs = loadArray("2LookPLL.txt");

        //switch to algs Algorithms window
        p2 = new PLL2AlgList(this, algs);
        p2.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn2LookPLLActionPerformed

    private void btnPLLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPLLActionPerformed
        //get algs algs
        algs = loadArray("PLL.txt");

        //switch to algs Algorithms window
        p = new PLLAlgList(this, algs);
        p.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnPLLActionPerformed

    private void btnOLLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOLLActionPerformed
        //get algs
        algs = loadArray("OLL.txt");

        //switch to algs Algorithms window
        o = new OLLAlgList(this, algs);
        o.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnOLLActionPerformed

    private void btn2LookOLL1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2LookOLL1ActionPerformed
        //get algs
        algs = loadArray("2LookOLL.txt");

        //switch to algs Algorithms window
        o2 = new OLL2AlgList(this, algs);
        o2.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn2LookOLL1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn2LookOLL1;
    private javax.swing.JButton btn2LookPLL;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnOLL;
    private javax.swing.JButton btnPLL;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
